<a href="https://colab.research.google.com/github/michael-karemi/my-ishh/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.ndim)

1


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)

2


In [ ]:
print(b.shape)

(2, 3)


In [ ]:
np.random.random((2, 3))

array([[0.86292001, 0.57069682, 0.37746215],
       [0.34259099, 0.62208804, 0.18984327]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2 ,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
c = np.array([[2.5, 8.6, 6.5], [7.5, 6.5, 9.9]])
d = np.array([[8.6, 4.8, 2.3], [5.5, 4.3, 7.7]])
print(c+d)

[[11.1 13.4  8.8]
 [13.  10.8 17.6]]


In [ ]:
print(c*d)

[[21.5  41.28 14.95]
 [41.25 27.95 76.23]]


In [ ]:
print((5*d)/c)

[[17.2         2.79069767  1.76923077]
 [ 3.66666667  3.30769231  3.88888889]]


In [17]:
print(a[0],[2])

6 [2]


In [21]:
c = b.reshape(3, 2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.random.randint(100, size = (5, 5, 5))

array([[[56, 69, 75,  1, 78],
        [48, 20, 13, 14, 72],
        [58, 14, 26,  5,  6],
        [ 2, 22, 21,  2, 22],
        [85, 74, 70, 14, 49]],

       [[45, 60, 22, 45, 45],
        [28, 41, 38, 37, 88],
        [95, 82, 25, 53, 44],
        [57, 83, 13, 25, 69],
        [10, 98, 75, 51, 87]],

       [[63,  0, 77, 88, 24],
        [86, 24, 15, 98, 40],
        [66, 89, 66, 88, 30],
        [81,  0,  9, 55, 92],
        [14, 46,  7, 89, 86]],

       [[88,  5, 63, 84, 68],
        [ 5, 24, 14, 15, 34],
        [17, 51, 27, 71, 49],
        [86, 89, 47,  7, 81],
        [47, 96, 92, 15, 12]],

       [[75, 69, 31, 19, 69],
        [57, 88, 76, 21,  4],
        [33, 98, 97, 24, 82],
        [70, 88, 78, 15, 83],
        [98, 45, 82, 44, 30]]])

In [27]:
d = np.random.binomial(n = 2, p = 0.5, size = 10)

array([1, 1, 0, 2, 0, 0, 1, 1, 2, 0])

In [28]:
np.mean(d)

5.533333333333334